### ISSUE TITLE
Division by 0 error on download (Termux/Android)

### ISSUE THREAD

**Issue by Midi-In** [r4yan2/emuparadise-dl#4]
emuparadise-dl crashes after selecting the ID and starting the download when running in Termux on 
Android (Latest Python 3.9.1 aarch64) with following traceback:

`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/emuparadise-dl", line 70, in <module>
    search_action(args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/emuparadise_dl/emuparadise_dl.py", line 285, in search_action
    downloader(backend, ID, args.output_directory, table[ID-1][1])
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/emuparadise_dl/emuparadise_dl.py", line 329, in downloader
    print_progress(0, total_length, prefix = realname, suffix = 'Speed', bar_length = 50)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/emuparadise_dl/helper.py", line 17, in print_progress
    percents = str_format.format(100 * (iteration / float(total)))
ZeroDivisionError: float division by zero`

**Comment by r4yan2** [comment]
Hello, thank you for reporting.
I've not been able to reproduce the issue on my device, but probably ba064f83e544cd14de600a1365416ecf665a2b9a will fix.
I've updated the PyPI as well, so you can update `emuparaside-dl` directly from `pip`. 
Please let me know if this is fixed so that I can close the issue.

**Comment by Midi-In** [comment]
Thank you, this update fixes the problem, feel free to close the issue!
